baseURL = "http://localhost:1313/"
languageCode = "zh-cn"
title = "你的名字"
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[params]
  env = "development"
  description = "一个个人网站"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowCodeCopyButtons = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "now"
    name = "Now"
    url = "/now/"
    weight = 3

  [[menu.main]]
    identifier = "labs"
    name = "Labs"
    url = "/labs/"
    weight = 4
